### ISSUE TITLE
ERROR CRHOME 90

### ISSUE THREAD

**Issue by gsmxcell** [ngeteng/Shopee-flash-sale-shopee-github#1]
Saya test di chrome terbaru versi 90 error gan

file shoppe.py line 30
chromedriver init.py line 35

**Comment by rizkihardinas** [comment]
sama

**Comment by ahmadrokhim87** [comment]
sama

**Comment by ahmadrokhim87** [comment]
sama juga

**Comment by rmdhfz** [comment]
Bantu jawab, pergi ke :
https://chromedriver.storage.googleapis.com/index.html

download chromedriver sesuai versi browser kalian, terus buka folder bot, rename chromedriver.exe menjadi chromedriverbackup.ext

ekstrak chromedriver hasil downlod, copy dan paste ke folder bot.

Selesai

**Comment by FhikarZul** [comment]
dilinux saya masih error gitu gan.

Traceback (most recent call last):
  File "/home/fii18/ShopeeBot/shopee.py", line 30, in <module>
    browser = UC.Chrome(options=options, enable_console_log=True)
  File "/usr/local/lib/python3.9/dist-packages/undetected_chromedriver/__init__.py", line 57, in __new__
    instance.__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'enable_console_log'

**Comment by rmdhfz** [comment]
@FhikarZul Coba :
browser = UC.Chrome(options=options)

**Comment by FhikarZul** [comment]
@rmdhfz udah bisa gan cuma muncul error gini gan.

[0809/141731.132:INFO:CONSOLE(1)] "Web MIDI will ask a permission to use even if the sysex is not specified in the MIDIOptions since around M82, around May 2020. See https://www.chromestatus.com/feature/5138066234671104 for more details.", source: https://deo.shopeemobile.com/shopee/shopee-pcmall-live-sg/assets/9219.3b0216037be906479069.js (1)

**Comment by jackr0se** [comment]
halo gan,ada yg sudah coba lagi blm?

ane barusan coba,pas sudah masuk menit 12:00:00 ,itu action nya apalagi ya?soalnya programnya seperti berhenti lama ga ada response lg,jadi terpaksa saya force closed cmd nya. mohon infonya. thanks ya
