### ISSUE TITLE
console_log

### ISSUE THREAD

**Issue by galang-cc** [ngeteng/Shopee-flash-sale-shopee-github#3]
Traceback (most recent call last):
  File "C:\Users\ASUS\Downloads\sopi\shopee.py", line 30, in <module>
    browser = UC.Chrome(options=options, enable_console_log=True)
  File "C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\undetected_chromedriver\__init__.py", line 57, in __new__
    instance.__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'enable_console_log'

**Comment by bangkitboss** [comment]
baca setettingnya [DISINI](https://www.sans.eu.org/2021/01/review-cara-kerja-bot-shopee-sans.html?m=1)  biar gak error
