### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections'

### ISSUE THREAD

**Issue by astronyu** [ngeteng/Shopee-flash-sale-shopee-github#5]
Hi, I'm trying this script but it gave me these every times. Could you help?

```
E:\Downloads\Compressed\Shopee-flash-sale-shopee-github-main>py shopee.py
Traceback (most recent call last):
  File "E:\Downloads\Compressed\Shopee-flash-sale-shopee-github-main\shopee.py", line 4, in <module>
    import undetected_chromedriver as UC
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\__init__.py", line 31, in <module>
    from . import v2
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\v2.py", line 21, in <module>
    from .cdp import CDP
  File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\undetected_chromedriver\cdp.py", line 6, in <module>
    from collections import Mapping, Sequence
ImportError: cannot import name 'Mapping' from 'collections' (C:\Users\X\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)```

**Comment by arrappp** [comment]
> Found the issue. First, DO NOT use python 3.10. Second, it need to have `driver = UC.Chrome()` or else it will give an error. Also, this script won't work if there are any Chromium fork installed such as Brave browser.
> 
> Any chance updating this to solve the issue with detecting other chromium version?

where to put  `driver = UC.Chrome()`  ?

**Comment by bangkitboss** [comment]
hello @astronyu 

you can read [HERE](https://www.sans.eu.org/2021/01/review-cara-kerja-bot-shopee-sans.html?m=1)  for more information.
